In [1]:
lst3 = [9, 8, 7, 6, 5]
lst3.reverse()

In [2]:
lst3

[5, 6, 7, 8, 9]

In [4]:
lst3.sort()

In [5]:
lst3

[5, 6, 7, 8, 9]

In [6]:
lst3.clear()
lst3

[]

In [10]:
 # tuple - immutable - () - any dts
tup = (1, 'MITT', 'MITM', 2026, 'mysuru', 'mysuru')

In [8]:
type(tup)

tuple

In [9]:
dir(tuple)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

In [11]:
tup.count('mysuru')

2

In [12]:
tup.index(2026)

3

In [13]:
tup1 = 1, 6, 6, 'mitt'
type(tup1)

tuple

In [14]:
# set - {} - ordered - unique
s = {9, 7, 5, 5, 5, 5}
type(s)

set

In [15]:
s

{5, 7, 9}

In [16]:
dir(set)

['__and__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']

In [17]:
s1 = {1, 3, 5}
s2 = {1, 3, 4}
# intersection
s1.intersection(s2)

{1, 3}

In [18]:
s1.union(s2)

{1, 3, 4, 5}

In [19]:
s1.difference(s2)

{5}

In [20]:
s2.difference(s1)

{4}

In [21]:
# dictionary - k:v - {} -keys are unique
dit = {'name':'shri','place':'mysuru',}
dit

{'name': 'shri', 'place': 'mysuru'}

In [22]:
type(dit)

dict

In [23]:
dit.keys()

dict_keys(['name', 'place'])

In [24]:
dit.values()

dict_values(['shri', 'mysuru'])

In [25]:
dt2 = {'name':['shridevi','chinnu','loki'],
        'age':[20, 19, 22],
         'place':['mysuru','tamil nadu','andhra']}

In [26]:
dt2

{'name': ['shridevi', 'chinnu', 'loki'],
 'age': [20, 19, 22],
 'place': ['mysuru', 'tamil nadu', 'andhra']}

In [28]:
l = 'RMS'
l[0:1] # n= n-1

'R'

In [29]:
l[0:2]

'RM'

In [30]:
l[1:]

'MS'

In [33]:
l[::-1]

'SMR'

In [37]:
for i in range(5):
    print(i)

0
1
2
3
4

In [38]:
for x in range(0, 11, 2):
    print(x)

0
2
4
6
8
10

In [39]:
for y in range(1, 12, 2):
    print(y)

1
3
5
7
9
11

In [43]:
for shridevi in range(50):
    print(shridevi)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49

In [50]:
# if
a = 50
b = 50
if a < b:
    print('true')

In [51]:
if a > b:
    print('true')
else:
    print('false')

false

In [52]:
if a>b:
    print('true')
elif a<b:
    print('false')
else:
    print('equal')

equal

In [53]:
# white loop
counter = 0
while counter <= 5:
    print(counter)
    counter += 1

0
1
2
3
4
5

In [54]:
counter = 5
while counter >= 0:
    print(counter)
    counter -= 1

5
4
3
2
1
0

In [55]:
counter = 5
while counter >= 0:
    print(counter * '*')
    counter -= 1

*****
****
***
**
*

In [56]:
# function - user define - custom
# def function name ();
def add(x, y):
    return x + y

In [57]:
x = 60
y = 40

In [58]:
add(60, 40)

100

In [59]:
def sub(x, y):
    return x - y

In [60]:
sub(90, 30)

60

In [61]:
def add(x, y, z):
    return x + y + z

In [62]:
add(9, 7, 4)

20

In [63]:
def add_num(*args):
    return sum(args)

In [64]:
add_num(9, 7, 89, 34, 56, 77, 12, 0, 45, 76, 99, 121, 34500, 24, 30)

35179

In [65]:
num_lst = [2, 5, 8, 9, 64, 33]
for i in num_lst:
    if i%2==0:
        print(i)

2
8
64

In [66]:
even_num = []
for i in num_lst:
    if i%2==0:
        even_num.append(i)

In [67]:
even_num

[2, 8, 64]

In [68]:
odd_num = []
for i in num_lst:
    if i%2!=0:
        odd_num.append(i)

In [69]:
odd_num

[5, 9, 33]

In [70]:
lc = [i for i in num_lst if i%2==0]
lc

[2, 8, 64]

In [71]:
lc = [i for i in num_lst if i%2!=0]
lc

[5, 9, 33]

In [72]:
# anonymous - lambda
add = lambda x, y: x + y

In [73]:
add(3, 4)

7

In [77]:
x = 1
while true:
    if x%5 == 0:
        break
     print(x)
        x + = 1

IndentationError: unindent does not match any outer indentation level (<string>, line 5)

In [1]:
#dataframe - 2d
data = {'Place':['Mysuru', 'Tumkur', 'Shivamoga', 'Manglore'], 
        'Food':['Mysuru Pak','Ragi Mudde', 'Dosa', 'Neer Dosa']}

In [2]:
df = pd.DataFrame(data)
df

NameError: name 'pd' is not defined

In [12]:
!pip install panda
import pandas as pd 
import numpy as py

Requirement already satisfied: panda in c:\users\student\appdata\local\programs\python\python312\lib\site-packages (0.3.1)
Requirement already satisfied: setuptools in c:\users\student\appdata\local\programs\python\python312\lib\site-packages (from panda) (84.0.0)
Requirement already satisfied: requests in c:\users\student\appdata\local\programs\python\python312\lib\site-packages (from panda) (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\student\appdata\local\programs\python\python312\lib\site-packages (from requests->panda) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\student\appdata\local\programs\python\python312\lib\site-packages (from requests->panda) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\student\appdata\local\programs\python\python312\lib\site-packages (from requests->panda) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\student\appdata\local\programs\python\python312\lib\site-packages (from requests->panda) (2026.7.22)

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np

In [4]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\Student\AppData\Local\Programs\Python\Python312\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Student\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Student\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Student\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Student\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
import pandas as pd
import numpy as np

In [6]:
x = [1, 7, 9, 78]
type(x)
se = pd.Series(x)
se

0     1
1     7
2     9
3    78
dtype: int64

In [7]:
# dataframe - 2d
data = {'place':['mysuru', 'tumkur', 'shivamoga', 'manglore'],
        'food':['mysuru pak','ragi mudde','dosa','neer dosa']}

In [8]:
df = pd.DataFrame(data)
df

       place        food
0     mysuru  mysuru pak
1     tumkur  ragi mudde
2  shivamoga        dosa
3   manglore   neer dosa

In [9]:
import pandas as pd
import numpy as np
df = pd.read_csv("Student_Behaviour.csv")

df.head()

,Certification Course,Gender,Department,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,hobbies,daily studing time,prefer to study in,salary expectation,Do you like your degree?,willingness to pursue a career based on their degree,social medai & video,Travelling Time,Stress Level,Financial Status,part-time job
0,No,Male,BCA,100.0,58.0,79.0,65.0,80.0,Video Games,0 - 30 minute,Morning,40000,No,50%,1.30 - 2 hour,30 - 60 minutes,Bad,Bad,No
1,No,Female,BCA,90.0,40.0,70.0,80.0,70.0,Cinema,30 - 60 minute,Morning,15000,Yes,75%,1 - 1.30 hour,0 - 30 minutes,Bad,Bad,No
2,Yes,Male,BCA,159.0,78.0,69.5,61.0,55.0,Cinema,1 - 2 Hour,Anytime,13000,Yes,50%,More than 2 hour,30 - 60 minutes,Awful,Bad,No
3,Yes,Female,BCA,147.0,20.0,70.0,59.0,58.0,Reading books,1 - 2 Hour,Anytime,1500000,No,50%,1.30 - 2 hour,0 - 30 minutes,Bad,good,No
4,No,Male,BCA,170.0,54.0,40.0,65.0,30.0,Video Games,30 - 60 minute,Morning,50000,Yes,25%,1.30 - 2 hour,30 - 60 minutes,Good,good,No

In [10]:
df.shape

(235, 19)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 19 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   Certification Course                                    235 non-null    str
 1   Gender                                                  235 non-null    str
 2   Department                                              235 non-null    str
 3   Height(CM)                                              235 non-null    float64
 4   Weight(KG)                                              235 non-null    float64
 5   10th Mark                                               235 non-null    float64
 6   12th Mark                                               235 non-null    float64
 7   college mark                                            235 non-null    float64
 8   hobbies                                                 235 non-null    str
 9   daily studing time                                      235 non-null    str
 10  prefer to study in                                      235 non-null    str
 11  salary expectation                                      235 non-null    int64
 12  Do you like your degree?                                235 non-null    str
 13  willingness to pursue a career based on their degree    235 non-null    str
 14  social medai & video                                    235 non-null    str
 15  Travelling Time                                         235 non-null    str
 16  Stress Level                                            235 non-null    str
 17  Financial Status                                        235 non-null    str
 18  part-time job                                           235 non-null    str
dtypes: float64(5), int64(1), str(13)
memory usage: 35.0 KB

In [12]:
df.describe()

,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,salary expectation
count,235.000000,235.000000,235.000000,235.000000,235.000000,2.350000e+02
mean,157.402128,60.803830,76.842128,68.780128,70.660553,3.248168e+04
std,21.510805,14.895844,13.050800,11.016533,15.727446,1.113146e+05
min,4.500000,20.000000,7.400000,45.000000,1.000000,0.000000e+00
25%,152.000000,50.000000,70.000000,60.000000,60.000000,1.500000e+04
50%,160.000000,60.000000,80.000000,69.000000,70.000000,2.000000e+04
75%,170.000000,70.000000,86.250000,76.000000,80.000000,2.500000e+04
max,192.000000,106.000000,98.000000,94.000000,100.000000,1.500000e+06

In [13]:
df.isnull().sum()

Certification Course                                      0
Gender                                                    0
Department                                                0
Height(CM)                                                0
Weight(KG)                                                0
10th Mark                                                 0
12th Mark                                                 0
college mark                                              0
hobbies                                                   0
daily studing time                                        0
prefer to study in                                        0
salary expectation                                        0
Do you like your degree?                                  0
willingness to pursue a career based on their degree      0
social medai & video                                      0
Travelling Time                                           0
Stress Level                                              0
Financial Status                                          0
part-time job                                             0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.Gender

0        Male
1      Female
2        Male
3      Female
4        Male
        ...
230      Male
231      Male
232    Female
233    Female
234    Female
Name: Gender, Length: 235, dtype: str

In [18]:
df['Certification Course']

0       No
1       No
2      Yes
3      Yes
4       No
      ...
230    Yes
231    Yes
232    Yes
233    Yes
234     No
Name: Certification Course, Length: 235, dtype: str

In [19]:
df.hobbies.unique()

<StringArray>
['Video Games', 'Cinema', 'Reading books', 'Sports']
Length: 4, dtype: str

In [21]:
df.columns

Index(['Certification Course', 'Gender', 'Department', 'Height(CM)',
       'Weight(KG)', '10th Mark', '12th Mark', 'college mark', 'hobbies',
       'daily studing time', 'prefer to study in', 'salary expectation',
       'Do you like your degree?',
       'willingness to pursue a career based on their degree  ',
       'social medai & video', 'Travelling Time ', 'Stress Level ',
       'Financial Status', 'part-time job'],
      dtype='str')

In [6]:
df.Stress Level.unique()

SyntaxError: invalid syntax (135482805.py, line 1)

In [24]:
df['part-time job'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [25]:
df['prefer to study in'].unique()

<StringArray>
['Morning', 'Anytime', 'Night']
Length: 3, dtype: str